### ISSUE TITLE
out of date API reference links

### ISSUE THREAD

**Issue by MaxPleaner** [yeahrb/yeah#49]
The link to http://rdoc.info/github/yeahrb/yeah/32a50f5/frames (4.0.2) is 404.

**Comment by aost** [comment]
Hm, that link used to work...

Either way, Yeah has been fundamentally changed for the upcoming version (0.5.0), so the latest released version (0.4.2) can be considered out-of-date.

The current best way to get familiar with the upcoming API is to look at the example project in ./example.

If you want to read the documentation for 0.4.2, you can checkout tag 0.4.2, execute `yard doc`, then open ./doc/index.html.

**Comment by aost** [comment]
So, uh... the example project has been removed from the codebase. The API for the upcoming version is continually in flux. Please wait for the next release for a usable (and useful) API.
